-- keytrack-candidate-glossary: managed keytrack-glossary-v1
-- Original MIT-licensed metadata; no input-history data.
return {
  ["不同"] = { en = "different", ja = "異なる" },
  ["世界"] = { en = "world", ja = "世界" },
  ["中午"] = { en = "noon", ja = "昼" },
  ["交期"] = { en = "delivery date", ja = "納期" },
  ["产品"] = { en = "product", ja = "製品" },
  ["今天"] = { en = "today", ja = "今日" },
  ["付款"] = { en = "payment", ja = "支払い" },
  ["以后"] = { en = "later", ja = "後で" },
  ["价格"] = { en = "price", ja = "価格" },
  ["休息"] = { en = "rest", ja = "休む" },
  ["会议"] = { en = "meeting", ja = "会議" },
  ["你好"] = { en = "hello", ja = "こんにちは" },
  ["保存"] = { en = "save", ja = "保存する" },
  ["修改"] = { en = "edit", ja = "修正する" },
  ["公交"] = { en = "bus", ja = "バス" },
  ["公园"] = { en = "park", ja = "公園" },
  ["关闭"] = { en = "close", ja = "閉じる" },
  ["再见"] = { en = "goodbye", ja = "さようなら" },
  ["准备"] = { en = "prepare", ja = "準備する" },
  ["医院"] = { en = "hospital", ja = "病院" },
  ["午餐"] = { en = "lunch", ja = "昼食" },
  ["发货"] = { en = "ship goods", ja = "発送する" },
  ["发送"] = { en = "send", ja = "送る" },
  ["合适"] = { en = "suitable", ja = "適切" },
  ["同事"] = { en = "colleague", ja = "同僚" },
  ["名字"] = { en = "name", ja = "名前" },
  ["周末"] = { en = "weekend", ja = "週末" },
  ["咖啡"] = { en = "coffee", ja = "コーヒー" },
  ["商店"] = { en = "shop", ja = "店" },
  ["地图"] = { en = "map", ja = "地図" },
  ["地铁"] = { en = "subway", ja = "地下鉄" },
  ["城市"] = { en = "city", ja = "都市" },
  ["复杂"] = { en = "complex", ja = "複雑" },
  ["天气"] = { en = "weather", ja = "天気" },
  ["学校"] = { en = "school", ja = "学校" },
  ["孩子"] = { en = "child", ja = "子供" },
  ["安全"] = { en = "safe", ja = "安全" },
  ["完成"] = { en = "complete", ja = "完了する" },
  ["客户"] = { en = "customer", ja = "顧客" },
  ["家人"] = { en = "family", ja = "家族" },
  ["家庭"] = { en = "household", ja = "家庭" },
  ["屏幕"] = { en = "screen", ja = "画面" },
  ["帮助"] = { en = "help", ja = "手伝う" },
  ["库存"] = { en = "stock", ja = "在庫" },
  ["开始"] = { en = "start", ja = "始める" },
  ["房间"] = { en = "room", ja = "部屋" },
  ["手机"] = { en = "mobile phone", ja = "携帯電話" },
  ["打开"] = { en = "open", ja = "開く" },
  ["报价"] = { en = "quotation", ja = "見積もり" },
  ["报告"] = { en = "report", ja = "報告書" },
  ["抱歉"] = { en = "sorry", ja = "ごめんなさい" },
  ["接收"] = { en = "receive", ja = "受け取る" },
  ["数量"] = { en = "quantity", ja = "数量" },
  ["文件"] = { en = "file", ja = "ファイル" },
  ["方便"] = { en = "convenient", ja = "便利" },
  ["日期"] = { en = "date", ja = "日付" },
  ["早上"] = { en = "morning", ja = "朝" },
  ["早餐"] = { en = "breakfast", ja = "朝食" },
  ["时间"] = { en = "time", ja = "時間" },
  ["明天"] = { en = "tomorrow", ja = "明日" },
  ["星期"] = { en = "week", ja = "週" },
  ["昨天"] = { en = "yesterday", ja = "昨日" },
  ["晚上"] = { en = "night", ja = "夜" },
  ["晚餐"] = { en = "dinner", ja = "夕食" },
  ["朋友"] = { en = "friend", ja = "友達" },
  ["机场"] = { en = "airport", ja = "空港" },
  ["机票"] = { en = "air ticket", ja = "航空券" },
  ["样品"] = { en = "sample", ja = "サンプル" },
  ["桌子"] = { en = "table", ja = "テーブル" },
  ["检查"] = { en = "check", ja = "点検する" },
  ["椅子"] = { en = "chair", ja = "椅子" },
  ["欢迎"] = { en = "welcome", ja = "ようこそ" },
  ["正确"] = { en = "correct", ja = "正しい" },
  ["水果"] = { en = "fruit", ja = "果物" },
  ["消息"] = { en = "message", ja = "メッセージ" },
  ["清楚"] = { en = "clear", ja = "明確" },
  ["火车"] = { en = "train", ja = "列車" },
  ["现在"] = { en = "now", ja = "今" },
  ["生日"] = { en = "birthday", ja = "誕生日" },
  ["电脑"] = { en = "computer", ja = "パソコン" },
  ["电话"] = { en = "phone call", ja = "電話" },
  ["相同"] = { en = "same", ja = "同じ" },
  ["确认"] = { en = "confirm", ja = "確認する" },
  ["空气"] = { en = "air", ja = "空気" },
  ["等待"] = { en = "wait", ja = "待つ" },
  ["简单"] = { en = "simple", ja = "簡単" },
  ["米饭"] = { en = "cooked rice", ja = "ご飯" },
  ["紧急"] = { en = "urgent", ja = "緊急" },
  ["结束"] = { en = "finish", ja = "終わる" },
  ["联系"] = { en = "contact", ja = "連絡" },
  ["茶叶"] = { en = "tea leaves", ja = "茶葉" },
  ["蔬菜"] = { en = "vegetables", ja = "野菜" },
  ["行李"] = { en = "luggage", ja = "荷物" },
  ["衣服"] = { en = "clothes", ja = "服" },
  ["表格"] = { en = "table", ja = "表" },
  ["订单"] = { en = "order", ja = "注文" },
  ["请问"] = { en = "excuse me", ja = "すみません" },
  ["谢谢"] = { en = "thank you", ja = "ありがとう" },
  ["质量"] = { en = "quality", ja = "品質" },
  ["资料"] = { en = "materials", ja = "資料" },
  ["路线"] = { en = "route", ja = "ルート" },
  ["车票"] = { en = "ticket", ja = "乗車券" },
  ["车站"] = { en = "station", ja = "駅" },
  ["通知"] = { en = "notice", ja = "通知" },
  ["邮件"] = { en = "email", ja = "メール" },
  ["酒店"] = { en = "hotel", ja = "ホテル" },
  ["重要"] = { en = "important", ja = "重要" },
  ["钥匙"] = { en = "key", ja = "鍵" },
  ["钱包"] = { en = "wallet", ja = "財布" },
  ["错误"] = { en = "mistake", ja = "間違い" },
  ["键盘"] = { en = "keyboard", ja = "キーボード" },
  ["问题"] = { en = "question", ja = "質問" },
  ["附件"] = { en = "attachment", ja = "添付ファイル" },
  ["雨伞"] = { en = "umbrella", ja = "傘" },
  ["面包"] = { en = "bread", ja = "パン" },
  ["面条"] = { en = "noodles", ja = "麺" },
  ["鞋子"] = { en = "shoes", ja = "靴" },
  ["饮料"] = { en = "drink", ja = "飲み物" },
  ["高铁"] = { en = "high-speed rail", ja = "高速鉄道" },
  ["鸡蛋"] = { en = "egg", ja = "卵" },
}
