-- keytrack-candidate-glossary: managed keytrack-glossary-v1+keytrack-work-terms-v1
-- Original MIT-licensed metadata; no input-history data.
return {
  ["不同"] = { en = "different", ja = "異なる" },
  ["不良品"] = { en = "defective goods", ja = "不良品" },
  ["世界"] = { en = "world", ja = "世界" },
  ["中午"] = { en = "noon", ja = "昼" },
  ["交期"] = { en = "delivery date", ja = "納期" },
  ["交货"] = { en = "delivery", ja = "納品" },
  ["产前样"] = { en = "pre-production sample", ja = "量産前サンプル" },
  ["产品"] = { en = "product", ja = "製品" },
  ["今天"] = { en = "today", ja = "今日" },
  ["付款"] = { en = "payment", ja = "支払い" },
  ["以后"] = { en = "later", ja = "後で" },
  ["价格"] = { en = "price", ja = "価格" },
  ["休息"] = { en = "rest", ja = "休む" },
  ["会议"] = { en = "meeting", ja = "会議" },
  ["你好"] = { en = "hello", ja = "こんにちは" },
  ["保修"] = { en = "warranty", ja = "保証" },
  ["保存"] = { en = "save", ja = "保存する" },
  ["修改"] = { en = "edit", ja = "修正する" },
  ["修模"] = { en = "mold repair", ja = "金型修理" },
  ["充电"] = { en = "charging", ja = "充電" },
  ["全检"] = { en = "full inspection", ja = "全数検査" },
  ["公交"] = { en = "bus", ja = "バス" },
  ["公园"] = { en = "park", ja = "公園" },
  ["公差"] = { en = "tolerance", ja = "公差" },
  ["关税"] = { en = "customs duty", ja = "関税" },
  ["关闭"] = { en = "close", ja = "閉じる" },
  ["再见"] = { en = "goodbye", ja = "さようなら" },
  ["准备"] = { en = "prepare", ja = "準備する" },
  ["出货"] = { en = "shipment", ja = "出荷" },
  ["加急"] = { en = "rush request", ja = "至急対応" },
  ["包装"] = { en = "packaging", ja = "包装" },
  ["医院"] = { en = "hospital", ja = "病院" },
  ["午餐"] = { en = "lunch", ja = "昼食" },
  ["原产地"] = { en = "country of origin", ja = "原産地" },
  ["发货"] = { en = "ship goods", ja = "発送する" },
  ["发送"] = { en = "send", ja = "送る" },
  ["合格品"] = { en = "accepted goods", ja = "合格品" },
  ["合格率"] = { en = "acceptance rate", ja = "合格率" },
  ["合适"] = { en = "suitable", ja = "適切" },
  ["同事"] = { en = "colleague", ja = "同僚" },
  ["名字"] = { en = "name", ja = "名前" },
  ["周末"] = { en = "weekend", ja = "週末" },
  ["咖啡"] = { en = "coffee", ja = "コーヒー" },
  ["售后"] = { en = "after-sales service", ja = "アフターサービス" },
  ["商业发票"] = { en = "commercial invoice", ja = "商業送り状" },
  ["商店"] = { en = "shop", ja = "店" },
  ["地图"] = { en = "map", ja = "地図" },
  ["地铁"] = { en = "subway", ja = "地下鉄" },
  ["城市"] = { en = "city", ja = "都市" },
  ["备料"] = { en = "material preparation", ja = "材料準備" },
  ["备货"] = { en = "stock preparation", ja = "出荷準備" },
  ["复杂"] = { en = "complex", ja = "複雑" },
  ["外壳"] = { en = "housing", ja = "筐体" },
  ["外贸"] = { en = "foreign trade", ja = "貿易" },
  ["天气"] = { en = "weather", ja = "天気" },
  ["学校"] = { en = "school", ja = "学校" },
  ["孩子"] = { en = "child", ja = "子供" },
  ["安全"] = { en = "safe", ja = "安全" },
  ["完成"] = { en = "complete", ja = "完了する" },
  ["定金"] = { en = "deposit", ja = "手付金" },
  ["客户"] = { en = "customer", ja = "顧客" },
  ["家人"] = { en = "family", ja = "家族" },
  ["家庭"] = { en = "household", ja = "家庭" },
  ["寄样"] = { en = "send samples", ja = "サンプル送付" },
  ["尺寸"] = { en = "dimensions", ja = "寸法" },
  ["尾款"] = { en = "balance payment", ja = "残金" },
  ["屏幕"] = { en = "screen", ja = "画面" },
  ["帮助"] = { en = "help", ja = "手伝う" },
  ["库存"] = { en = "stock", ja = "在庫" },
  ["延期"] = { en = "postponement", ja = "延期" },
  ["延迟"] = { en = "delay", ja = "遅延" },
  ["开始"] = { en = "start", ja = "始める" },
  ["开模"] = { en = "mold making", ja = "金型製作" },
  ["彩盒"] = { en = "printed box", ja = "印刷箱" },
  ["房间"] = { en = "room", ja = "部屋" },
  ["手机"] = { en = "mobile phone", ja = "携帯電話" },
  ["打开"] = { en = "open", ja = "開く" },
  ["打样"] = { en = "prototyping", ja = "試作" },
  ["报价"] = { en = "quotation", ja = "見積もり" },
  ["报关"] = { en = "customs declaration", ja = "通関申告" },
  ["报告"] = { en = "report", ja = "報告書" },
  ["抱歉"] = { en = "sorry", ja = "ごめんなさい" },
  ["抽检"] = { en = "sampling inspection", ja = "抜取検査" },
  ["排期"] = { en = "schedule", ja = "日程調整" },
  ["接收"] = { en = "receive", ja = "受け取る" },
  ["提单"] = { en = "bill of lading", ja = "船荷証券" },
  ["数量"] = { en = "quantity", ja = "数量" },
  ["文件"] = { en = "file", ja = "ファイル" },
  ["方便"] = { en = "convenient", ja = "便利" },
  ["日期"] = { en = "date", ja = "日付" },
  ["早上"] = { en = "morning", ja = "朝" },
  ["早餐"] = { en = "breakfast", ja = "朝食" },
  ["时间"] = { en = "time", ja = "時間" },
  ["明天"] = { en = "tomorrow", ja = "明日" },
  ["星期"] = { en = "week", ja = "週" },
  ["昨天"] = { en = "yesterday", ja = "昨日" },
  ["晚上"] = { en = "night", ja = "夜" },
  ["晚餐"] = { en = "dinner", ja = "夕食" },
  ["朋友"] = { en = "friend", ja = "友達" },
  ["机场"] = { en = "airport", ja = "空港" },
  ["机票"] = { en = "air ticket", ja = "航空券" },
  ["材料"] = { en = "material", ja = "材料" },
  ["条码"] = { en = "barcode", ja = "バーコード" },
  ["标签"] = { en = "label", ja = "ラベル" },
  ["样品"] = { en = "sample", ja = "サンプル" },
  ["样品费"] = { en = "sample fee", ja = "サンプル代" },
  ["样机"] = { en = "prototype", ja = "試作機" },
  ["样板"] = { en = "sample unit", ja = "見本" },
  ["桌子"] = { en = "table", ja = "テーブル" },
  ["检查"] = { en = "check", ja = "点検する" },
  ["检验报告"] = { en = "inspection report", ja = "検査報告書" },
  ["椅子"] = { en = "chair", ja = "椅子" },
  ["模具"] = { en = "mold", ja = "金型" },
  ["欢迎"] = { en = "welcome", ja = "ようこそ" },
  ["正确"] = { en = "correct", ja = "正しい" },
  ["水果"] = { en = "fruit", ja = "果物" },
  ["注塑"] = { en = "injection molding", ja = "射出成形" },
  ["测试"] = { en = "test", ja = "試験" },
  ["消息"] = { en = "message", ja = "メッセージ" },
  ["清关"] = { en = "customs clearance", ja = "通関" },
  ["清楚"] = { en = "clear", ja = "明確" },
  ["火车"] = { en = "train", ja = "列車" },
  ["现在"] = { en = "now", ja = "今" },
  ["生产周期"] = { en = "production lead time", ja = "生産期間" },
  ["生日"] = { en = "birthday", ja = "誕生日" },
  ["电池"] = { en = "battery", ja = "電池" },
  ["电脑"] = { en = "computer", ja = "パソコン" },
  ["电话"] = { en = "phone call", ja = "電話" },
  ["相同"] = { en = "same", ja = "同じ" },
  ["确认"] = { en = "confirm", ja = "確認する" },
  ["确认样"] = { en = "approved sample", ja = "承認サンプル" },
  ["空气"] = { en = "air", ja = "空気" },
  ["等待"] = { en = "wait", ja = "待つ" },
  ["简单"] = { en = "simple", ja = "簡単" },
  ["米饭"] = { en = "cooked rice", ja = "ご飯" },
  ["紧急"] = { en = "urgent", ja = "緊急" },
  ["结束"] = { en = "finish", ja = "終わる" },
  ["结构"] = { en = "structure", ja = "構造" },
  ["维修"] = { en = "repair", ja = "修理" },
  ["缺陷"] = { en = "defect", ja = "不具合" },
  ["联系"] = { en = "contact", ja = "連絡" },
  ["脱模"] = { en = "demolding", ja = "離型" },
  ["茶叶"] = { en = "tea leaves", ja = "茶葉" },
  ["蔬菜"] = { en = "vegetables", ja = "野菜" },
  ["行李"] = { en = "luggage", ja = "荷物" },
  ["衣服"] = { en = "clothes", ja = "服" },
  ["表格"] = { en = "table", ja = "表" },
  ["装箱单"] = { en = "packing list", ja = "梱包明細書" },
  ["装配"] = { en = "assembly", ja = "組立" },
  ["订单"] = { en = "order", ja = "注文" },
  ["试产"] = { en = "pilot production", ja = "試験生産" },
  ["试模"] = { en = "mold trial", ja = "成形試験" },
  ["试用"] = { en = "trial use", ja = "試用" },
  ["询盘"] = { en = "inquiry", ja = "引き合い" },
  ["说明书"] = { en = "user manual", ja = "取扱説明書" },
  ["请问"] = { en = "excuse me", ja = "すみません" },
  ["谢谢"] = { en = "thank you", ja = "ありがとう" },
  ["质检"] = { en = "quality inspection", ja = "品質検査" },
  ["质量"] = { en = "quality", ja = "品質" },
  ["贸易条款"] = { en = "trade terms", ja = "取引条件" },
  ["资料"] = { en = "materials", ja = "資料" },
  ["起订量"] = { en = "minimum order quantity", ja = "最小発注数量" },
  ["路线"] = { en = "route", ja = "ルート" },
  ["车票"] = { en = "ticket", ja = "乗車券" },
  ["车站"] = { en = "station", ja = "駅" },
  ["运费"] = { en = "freight cost", ja = "送料" },
  ["返修"] = { en = "repair", ja = "修理" },
  ["返工"] = { en = "rework", ja = "手直し" },
  ["返样"] = { en = "return sample", ja = "サンプル返送" },
  ["退货"] = { en = "goods return", ja = "返品" },
  ["通知"] = { en = "notice", ja = "通知" },
  ["邮件"] = { en = "email", ja = "メール" },
  ["配件"] = { en = "accessories", ja = "付属品" },
  ["酒店"] = { en = "hotel", ja = "ホテル" },
  ["重要"] = { en = "important", ja = "重要" },
  ["量产"] = { en = "mass production", ja = "量産" },
  ["量产样"] = { en = "production sample", ja = "量産サンプル" },
  ["钥匙"] = { en = "key", ja = "鍵" },
  ["钱包"] = { en = "wallet", ja = "財布" },
  ["错误"] = { en = "mistake", ja = "間違い" },
  ["键盘"] = { en = "keyboard", ja = "キーボード" },
  ["问题"] = { en = "question", ja = "質問" },
  ["附件"] = { en = "attachment", ja = "添付ファイル" },
  ["雨伞"] = { en = "umbrella", ja = "傘" },
  ["面包"] = { en = "bread", ja = "パン" },
  ["面条"] = { en = "noodles", ja = "麺" },
  ["鞋子"] = { en = "shoes", ja = "靴" },
  ["预付款"] = { en = "advance payment", ja = "前払い" },
  ["饮料"] = { en = "drink", ja = "飲み物" },
  ["验货"] = { en = "goods inspection", ja = "商品検査" },
  ["高铁"] = { en = "high-speed rail", ja = "高速鉄道" },
  ["鸡蛋"] = { en = "egg", ja = "卵" },
}
